Add version 0.0.5 from google code tarball

diff --git a/bin/new_pkg b/bin/new_pkg
--- a/bin/new_pkg
+++ b/bin/new_pkg
@@ -80,34 +80,44 @@ check_info() {
 
 set -e
 
-[ -r ~/.sbo-dev-helver.cfg ] && . ~/.sbo-dev-helver.cfg
-
-if [ -z "$SBO_TEMPLATES" ]; then
-	echo "please tell me where are the templates located with SBO_TEMPLATES variable."
-	exit 3
-fi
 if [ -z "$1" -o "$1" = '--help' -o "$1" = '-h' ]; then
 	echo "$usage"
 	exit
+fi
+
+[ -r ~/.sbo-dev-helper.cfg ] && . ~/.sbo-dev-helper.cfg
+if [ -z "$SBO_TEMPLATES" ]; then
+	echo "$usage"
+	echo
+	echo "Please tell me where are the templates located with SBO_TEMPLATES variable."
+	exit 3
 fi
 
 PKGNAM=$(basename $1)
 PKGDIR=$1
 shift
 
+# non-fatal check
+if [ -e $PKGDIR/doinst.sh ]; then
+	check_same $PKGDIR/doinst.sh $SBO_TEMPLATES/doinst.sh && \
+	echo "WARNING: $PKGDIR/doinst.sh not modified?..."
+fi
+
+# fatal check
 if check_same $PKGDIR/$PKGNAM.SlackBuild $SBO_TEMPLATES/template.SlackBuild; then
-	echo "$PKGDIR/$PKGNAM.SlackBuild not modified?..."
+	echo "ERROR: $PKGDIR/$PKGNAM.SlackBuild not modified?..."
 	exit 1
 fi
 if [ "$(cat $PKGDIR/slack-desc | md5sum -)" = \
      "$(sed -e "s/appname:/$PKGNAM:/" $SBO_TEMPLATES/slack-desc | md5sum -)" ]; then
-	echo "ERROR: slack-desc: $PKGDIR/slack-desc not adjusted?..."
+	echo "ERROR: $PKGDIR/slack-desc not adjusted?..."
 	exit 1
 fi
 if check_same $PKGDIR/README $SBO_TEMPLATES/README; then
-	echo "ERROR: README: $PKGDIR/README not modified?..."
+	echo "ERROR: $PKGDIR/README not modified?..."
 	exit 1
 fi
+
 check_info
 
 echo
diff --git a/bin/update_sbo_tpl b/bin/update_sbo_tpl
--- a/bin/update_sbo_tpl
+++ b/bin/update_sbo_tpl
@@ -1,28 +1,45 @@
-#!/bin/sh
+#!/bin/zsh
 
-[ -r ~/.sbo-dev-helver.cfg ] && . ~/.sbo-dev-helver.cfg
+usage="update_sbo_tpl
 
+Synchronize the templates directory with official templates.
+
+Simple as it is, no option is needed. I will warn you if there is any
+differences and save the new file with a .new suffix in \$SBO_TEMPLATES.
+Stay tuned. ;-)"
+
+if [ "$1" = '--help' -o "$1" = '-h' ]; then
+	echo "$usage"
+	exit
+elif [ $# -ne 0 ]; then
+	echo "WARNING: no argument needed. Ignored $@"
+fi
+
+[ -r ~/.sbo-dev-helper.cfg ] && . ~/.sbo-dev-helper.cfg
 if [ -z "$SBO_TEMPLATES" ]; then
 	echo "please tell me where are the templates located with SBO_TEMPLATES variable."
 	exit 3
 fi
 
-cd $SBO_TEMPLATES
-rm -rf new
+tmp_dir=$(mktemp -d) || { echo "Cannot creat temporary dir."; exit 1 }
 
-lftp -c 'mirror http://www.slackbuilds.org/templates/ new'
+cd $tmp_dir
+lftp -c 'mirror http://www.slackbuilds.org/templates/ .'
 
-for newf in new/*; do
-	oldf=$(basename $newf)
+for newf in ./*; do
+	oldf=$SBO_TEMPLATES/$(basename $newf)
 	if [ "$(cat $oldf 2>/dev/null | md5sum -)" != "$(cat $newf 2>/dev/null | md5sum -)" ]; then
+		mv $newf $oldf.new
 		printf "\t$oldf have changed!!!\n"
 		printf "\tConsider update your SlackBuilds!\n"
-		printf "\tNew template file restored as $SBO_TEMPLATES/new/$oldf\n"
 		printf "\n"
 		dirty=1
 	else
 		rm $newf
 	fi
 done
+rmdir $tmp_dir
 
-[ "$dirty" ] && exit 1
+if [ -n "$dirty" ]; then
+	exit 1
+fi
